### ISSUE TITLE
The function torch.cuda.empty_cache() is missing.

### ISSUE THREAD

**Issue by lintao185** [dotnet/TorchSharp#1327] opened 2024-06-09 12:47 UTC
The function torch.cuda.empty_cache() is missing.

**Comment by yueyinqiu** [comment] 2024-06-09 16:16
might be similar to #1194

**Comment by yueyinqiu** [comment] 2024-06-09 16:17
and for the memory issues... It's really hard to help you if you don't provide a way to reproduce them.

**Comment by lintao185** [comment] 2024-06-09 16:27
The strange thing is that I added torch.NewDisposeScope() to every function, but it still leads to memory leaks. However, when I write a standalone demo, there are no issues. It's very puzzling, and I can't figure it out.

**Comment by lintao185** [comment] 2024-06-09 16:29
I'm giving up for now. I'll come back to it after some time; maybe there will be a surprise.😊😊😊

**Comment by lintao185** [comment] 2024-06-10 02:48
It seems I found the reason: TorchSharp doesn't have torch.cuda.amp, so more memory is needed to store the computation graph during training.

**Comment by NiklasGustafsson** [comment] 2024-06-10 14:48
Torch doesn't seem to release GPU memory once it's been allocated, unless you call empty_cache(). It holds onto it for future needs.

This is a duplicate of https://github.com/dotnet/TorchSharp/issues/892, where I discussed some of the complications with implementing it, so I'll close this issue and keep the old one open.

**Closed by NiklasGustafsson** 2024-06-10 14:48 UTC
