### ISSUE TITLE
The training does not converge and the reason cannot be found.

### ISSUE THREAD

**Issue by williamlzw** [dotnet/TorchSharp#819] opened 2022-10-25 15:23 UTC
I ported the pytorch code to c#, the loss dropped to a certain level during training and no longer decreased, and the training could not converge. I can't find the reason.

using static TorchSharp.torch.nn;
using static TorchSharp.torch;
using TorchSharp.Modules;

namespace MicroOCR
{
    public class CRNN : Module<Tensor, Tensor>
    {
        private readonly ModuleDict<Module<Tensor, Tensor>> submodules = new ModuleDict<Module<Tensor, Tensor>>();

        public CRNN(long inputChannels = 3, long nh = 256, long numClass = 62) : base("CRNN")
        {
            submodules.Add("conv1", Conv2d(inputChannels, 64, 3, 1, 1));
            submodules.Add("relu1", ReLU(true));
            submodules.Add("maxpool1", MaxPool2d(2, 2));

            submodules.Add("conv2", Conv2d(64, 128, 3, 1, 1));
            submodules.Add("relu2", ReLU(true));
            submodules.Add("maxpool2", MaxPool2d(2, 2));

            submodules.Add("conv3", Conv2d(128, 256, (3,3), (2,1), (1,1)));
            submodules.Add("bn3", BatchNorm2d(256));
            submodules.Add("relu3", ReLU(true));

            submodules.Add("conv4", Conv2d(256, 256, 3, 1, 1));
            submodules.Add("relu4", ReLU(true));
            submodules.Add("maxpool4", MaxPool2d(2, 1, 1));

            submodules.Add("conv5", Conv2d(256, 512, (3, 3), (2, 1), (1, 1)));
            submodules.Add("bn5", BatchNorm2d(512));
            submodules.Add("relu5", ReLU(true));

            submodules.Add("conv6", Conv2d(512, 512, 3, 1, 1));
            submodules.Add("relu6", ReLU(true));
            submodules.Add("maxpool6", MaxPool2d(2, 1, 1));

            submodules.Add("conv7", Conv2d(512, 512, (3, 3), (2, 1), (0, 0)));
            submodules.Add("bn7", BatchNorm2d(512));
            submodules.Add("relu7", ReLU(true));

            submodules.Add("fc1", Linear(512, nh / 2));
            submodules.Add("fc2", Linear(nh / 2, numClass));
            RegisterComponents();
        }
        public override Tensor forward(Tensor input)
        {
            var x = submodules["conv1"].forward(input);
            x = submodules["relu1"].forward(x);
            x = submodules["maxpool1"].forward(x);
            x = submodules["conv2"].forward(x);
            x = submodules["relu2"].forward(x);
            x = submodules["maxpool2"].forward(x);
            x = submodules["conv3"].forward(x);
            x = submodules["bn3"].forward(x);
            x = submodules["relu3"].forward(x);
            x = submodules["conv4"].forward(x);
            x = submodules["relu4"].forward(x);
            x = submodules["maxpool4"].forward(x);
            x = submodules["conv5"].forward(x);
            x = submodules["bn5"].forward(x);
            x = submodules["relu5"].forward(x);
            x = submodules["conv6"].forward(x);
            x = submodules["relu6"].forward(x);
            x = submodules["maxpool6"].forward(x);
            x = submodules["conv7"].forward(x);
            x = submodules["bn7"].forward(x);
            x = submodules["relu7"].forward(x);
            x = x.squeeze(2);
            x = x.permute(2, 0, 1);
            x = submodules["fc1"].forward(x);
            x = submodules["fc2"].forward(x);
            x = x.permute(1, 0, 2);
            return x;
        }
    }
}

**Comment by NiklasGustafsson** [comment] 2022-10-25 16:22
>> and the training could not converge. I can't find the reason.

But it does in Python with the same data set, batch size, etc.? Usually, when the training converges at a disappointing level, I would look at using a larger data set, but if there's a difference between training with PyTorch and training with TorchSharp, it's something we should look into.

Also, what does the covergence of accuracy when measured against the validation data set look like? Does that also converge at a disappointing level?

**Comment by NiklasGustafsson** [comment] 2022-10-25 16:29
BTW, this reminds me that `Tensor.squeeze_()` (in-place variant) is missing.

**Comment by GeorgeS2019** [comment] 2022-10-27 02:48
```cs
using static TorchSharp.torch.nn;
using static TorchSharp.torch;
using TorchSharp.Modules;

namespace MicroOCR
{
public class CRNN : Module<Tensor, Tensor>
{
private readonly ModuleDict<Module<Tensor, Tensor>> submodules = new ModuleDict<Module<Tensor, Tensor>>();

    public CRNN(long inputChannels = 3, long nh = 256, long numClass = 62) : base("CRNN")
    {
        submodules.Add("conv1", Conv2d(inputChannels, 64, 3, 1, 1));
        submodules.Add("relu1", ReLU(true));
        submodules.Add("maxpool1", MaxPool2d(2, 2));

        submodules.Add("conv2", Conv2d(64, 128, 3, 1, 1));
        submodules.Add("relu2", ReLU(true));
        submodules.Add("maxpool2", MaxPool2d(2, 2));

        submodules.Add("conv3", Conv2d(128, 256, (3,3), (2,1), (1,1)));
        submodules.Add("bn3", BatchNorm2d(256));
        submodules.Add("relu3", ReLU(true));

        submodules.Add("conv4", Conv2d(256, 256, 3, 1, 1));
        submodules.Add("relu4", ReLU(true));
        submodules.Add("maxpool4", MaxPool2d(2, 1, 1));

        submodules.Add("conv5", Conv2d(256, 512, (3, 3), (2, 1), (1, 1)));
        submodules.Add("bn5", BatchNorm2d(512));
        submodules.Add("relu5", ReLU(true));

        submodules.Add("conv6", Conv2d(512, 512, 3, 1, 1));
        submodules.Add("relu6", ReLU(true));
        submodules.Add("maxpool6", MaxPool2d(2, 1, 1));

        submodules.Add("conv7", Conv2d(512, 512, (3, 3), (2, 1), (0, 0)));
        submodules.Add("bn7", BatchNorm2d(512));
        submodules.Add("relu7", ReLU(true));

        submodules.Add("fc1", Linear(512, nh / 2));
        submodules.Add("fc2", Linear(nh / 2, numClass));
        RegisterComponents();
    }
    public override Tensor forward(Tensor input)
    {
        var x = submodules["conv1"].forward(input);
        x = submodules["relu1"].forward(x);
        x = submodules["maxpool1"].forward(x);
        x = submodules["conv2"].forward(x);
        x = submodules["relu2"].forward(x);
        x = submodules["maxpool2"].forward(x);
        x = submodules["conv3"].forward(x);
        x = submodules["bn3"].forward(x);
        x = submodules["relu3"].forward(x);
        x = submodules["conv4"].forward(x);
        x = submodules["relu4"].forward(x);
        x = submodules["maxpool4"].forward(x);
        x = submodules["conv5"].forward(x);
        x = submodules["bn5"].forward(x);
        x = submodules["relu5"].forward(x);
        x = submodules["conv6"].forward(x);
        x = submodules["relu6"].forward(x);
        x = submodules["maxpool6"].forward(x);
        x = submodules["conv7"].forward(x);
        x = submodules["bn7"].forward(x);
        x = submodules["relu7"].forward(x);
        x = x.squeeze(2);
        x = x.permute(2, 0, 1);
        x = submodules["fc1"].forward(x);
        x = submodules["fc2"].forward(x);
        x = x.permute(1, 0, 2);
        return x;
    }
}
}
```

**Comment by williamlzw** [comment] 2022-10-28 15:02
https://github.com/williamlzw/MicroOCR.NET
https://github.com/williamlzw/MicroOCR
This is the c# code and the pytorch code.

**Comment by NiklasGustafsson** [comment] 2022-10-28 15:43
@williamlzw -- it looks like the data set is 10,000 letters, based on the Python. That sounds small. Does it converge at a higher precision in Python than in .NET for the same size data set?

**Comment by williamlzw** [comment] 2022-10-29 01:03
Pytorch training only needs 2 to 3 epochs to converge to an accuracy of more than 95%.genimage.py of the c # project is the generated data script.

**Comment by NiklasGustafsson** [comment] 2022-10-31 20:43
Thanks for sharing the code. I will take a look at it when I have a chance. Unfortunately, this week looks like it's going to be intense for me, so it might not be until next week that I get to it.

**Comment by williamlzw** [comment] 2022-11-01 05:44
## gen data
run gendata.py,10000 samples for training, 500 samples for verification.

## train
Modify the TrainRoot, TestRoot, TrainLabel, TestLabel, and VocabularyPath of the Program.cs file.
Then run it.

**Comment by NiklasGustafsson** [comment] 2022-11-01 23:03
@williamlzw -- I can reproduce the problem on my machine.

**Comment by NiklasGustafsson** [comment] 2022-11-02 18:34
@williamlzw -- I now have the .NET version converging at the same rate as the Python version.

Here's the end of epoch 20:

```
Train:[epoch 20/20][step 1250/1250 (100%] lr:0.00090 Loss:1.8964 Word Acc:0.9254 Char Acc:0.9600 Cost time:34s Estimated time:0s
Eval:[step 63/63 (100)%] Loss:0.5252 Word Acc:0.8500 Char Acc:0.9500 Cost time:0s
```

I did a few things, including switching the LR scheduler, as I mentioned. I also added memory-management code to both the training loop and the outermost model `forward()` function. I also changed the use of ModuleList to Sequential. Those have nothing to do with getting things to work.

What did, finally, make it work was to switch to using `torchvision.io.read_image()` to load the images. I made some changes to Dataset.cs and CollateFn.cs, where I hard-coded the image size.

I've posted the modified code on my fork of your repo: https://github.com/NiklasGustafsson/MicroOCR.NET

**Comment by NiklasGustafsson** [comment] 2022-11-02 21:27
I moved up to training on 100,000 images.

![image](https://user-images.githubusercontent.com/1791495/199605647-8b22a4a1-1051-4a93-a37c-7c7876584652.png)

The x-axis is not epochs, but validation steps, runs once every 100 batches.

**Comment by williamlzw** [comment] 2022-11-03 01:03
Thank you very much!The problem lies in the model definition and the use of opencvsharp to read data.

**Comment by NiklasGustafsson** [comment] 2022-11-03 01:06
Not so much the model definition (although it would likely run out of memory for larger data sizes, batch sizes, etc. It was the I/O that something was wrong with (don't know what).

It's a really cool example -- when it's working and cleaned up, commented, etc. it would be a great addition to dotnet/TorchSharpExamples.

**Comment by NiklasGustafsson** [comment] 2022-11-03 01:08
By the way, I switched to using the ReduceOnPlateauLR in my fork of the repo.

**Comment by NiklasGustafsson** [comment] 2022-11-03 01:43
@williamlzw -- can we close this issue now?

**Comment by williamlzw** [comment] 2022-11-03 02:19
ok.The following is my modified collatefn, which supports samples of any length.

using TorchSharp;

namespace MicroOCR
{
    public static class CollateFn
    {

        public static BatchItem Collate(IEnumerable<TextLineDataSetItem> items, torch.Device device)
        {
            
            var itemList = items.ToList<TextLineDataSetItem>();
            var transform = torchvision.transforms.ConvertImageDType(torch.ScalarType.Float32); 
            List<int> allImageWidth = new List<int>();       
            foreach (var item in items)
            {
                allImageWidth.Add((int)((double)32 / item.image.shape[1] * item.image.shape[2]));
            }
            var maxImgWidth = allImageWidth.Max();
            maxImgWidth = (int)Math.Ceiling((double)maxImgWidth / 8) * 8;

            List<torch.Tensor> resizeImgTensor = new List<torch.Tensor>();
            List<string> labels = new List<string>();
            for (int i = 0; i < items.Count(); i++)
            {
                labels.Add(itemList[i].label);
                int newWidth = (int)((double)32 / itemList[i].image.shape[1] * itemList[i].image.shape[2]);
                var resizeOperator = torchvision.transforms.Resize(32, newWidth);
                long[] padding = { 0, (long)maxImgWidth - newWidth, 0, 0};
                var padOperator = torchvision.transforms.Pad(padding);
                var img = itemList[i].image;
                var imgTensor = padOperator.forward(resizeOperator.forward(transform.forward(img)));         
                resizeImgTensor.Add(imgTensor);
            }
            var images = torch.stack(resizeImgTensor).to(device);
            return new BatchItem
            {
                labels = labels,
                images = images
            };
        }
    }
}

**Closed** 2022-11-03 02:22 UTC

**Comment by NiklasGustafsson** [comment] 2022-11-03 03:46
Hmmm

The images that the MicroOCR and MicroOCR.NET train on are different -- the former are captchas, which are harder than the ones generated by the gendata.py in the latter repo. How come?

**Comment by williamlzw** [comment] 2022-11-03 04:05
Yes. MicroOCR.NET Simple samples are used to verify whether the torch sharp training can converge.

**Comment by NiklasGustafsson** [comment] 2022-11-03 04:23
Okay, got it. When I ran the .NET training above, it was on the harder images. With the simple images, it goes to 1.00 word accuracy after one or two epochs.
