### ISSUE TITLE
[Bug] manual_seed not work

### ISSUE THREAD

**Issue by ChengYen-Tang** [dotnet/TorchSharp#972] opened 2023-04-02 14:38 UTC
python:
```
>>> import torch
>>> torch.manual_seed(0)
<torch._C.Generator object at 0x7f90af3adf30>
>>> torch.randn(1, 2)
tensor([[ 1.5410, -0.2934]])
>>> torch.randn(1, 2)
tensor([[-2.1788,  0.5684]])
>>> torch.manual_seed(0)
<torch._C.Generator object at 0x7f90af3adf30>
>>> torch.randn(1, 2)
tensor([[ 1.5410, -0.2934]])
>>> torch.randn(1, 2)
tensor([[-2.1788,  0.5684]])
```
<img width="666" alt="image" src="https://user-images.githubusercontent.com/32535494/229359689-ea573ffa-bba8-4bb3-9e00-e8d7bcb8737c.png">

C#
```
manual_seed(0);
Console.WriteLine(randn(new long[] { 1, 2 }).ToString(style: TorchSharp.TensorStringStyle.Default));
Console.WriteLine(randn(new long[] { 1, 2 }).ToString(style: TorchSharp.TensorStringStyle.Default));

manual_seed(0);
Console.WriteLine(randn(new long[] { 1, 2 }).ToString(style: TorchSharp.TensorStringStyle.Default));
Console.WriteLine(randn(new long[] { 1, 2 }).ToString(style: TorchSharp.TensorStringStyle.Default));
```
<img width="616" alt="image" src="https://user-images.githubusercontent.com/32535494/229359775-8508b428-49fc-4fd7-b589-916652c09673.png">

**Comment by NiklasGustafsson** [comment] 2023-04-04 16:53
Duplicate of #962, which is fixed and will be in the next release.

**Closed** 2023-04-04 16:54 UTC
