### ISSUE TITLE
Can't load LibTorchSharp.dll in .NET Framework v4.8

### ISSUE THREAD

**Issue by ArchiDog1998** [dotnet/TorchSharp#640] opened 2022-06-26 02:11 UTC
I've put my .NET Framework v4.8 file and another c++ libtorch file into the libtorch/lib folder. But I got this Exception in C# file, but work fine with c++ file. I've put the LibTorchSharp.dll in the same folder.

> 1. Solution exception:This application or script uses TorchSharp but doesn't contain a reference to libtorch-cpu-win-x64, Version=1.11.0.1.
Consider referencing one of the combination packages TorchSharp-cpu, TorchSharp-cuda-linux, TorchSharp-cuda-windows or call System.Runtime.InteropServices.NativeLibrary.Load(path-to-LibTorchSharp.dll) explicitly for a Python install of pytorch. See https://github.com/dotnet/TorchSharp/issues/169.".
For CUDA, you may need to call 'TorchSharp.torch.InitializeDeviceType(TorchSharp.DeviceType.CUDA)' before any use of TorchSharp CUDA packages from scripts or notebooks.
Trace from LoadNativeBackend:
TorchSharp: LoadNativeBackend: Initialising native backend, useCudaBackend = False
Step 1 - First try regular load of native libtorch binaries.
    Trying to load native component torch_cpu relative to E:\Software\Pytorch\libtorch-win-shared-with-deps-1.11.0+cu113\libtorch\lib\TorchSharp.dll
    Trying to load native component LibTorchSharp relative to E:\Software\Pytorch\libtorch-win-shared-with-deps-1.11.0+cu113\libtorch\lib\TorchSharp.dll
    Failed to load native component LibTorchSharp relative to E:\Software\Pytorch\libtorch-win-shared-with-deps-1.11.0+cu113\libtorch\lib\TorchSharp.dll
    Result from regular native load of LibTorchSharp is False
Step 3 - Alternative load from consolidated directory of native binaries from nuget packages
    torchsharpLoc = E:\Software\Pytorch\libtorch-win-shared-with-deps-1.11.0+cu113\libtorch\lib
    packagesDir = E:\Software
    torchsharpHome = E:\Software\Pytorch\libtorch-win-shared-with-deps-1.11.0+cu113
    Giving up, TorchSharp.dll does not appear to have been loaded from package directories

In .NET Framework v4.8, there is no function called System.Runtime.InteropServices.NativeLibrary.Load(). Is there any way to load file in .NET Framework v4.8? Thanks a lot.

**Comment by NiklasGustafsson** [comment] 2022-06-28 18:02
@tarekgh -- you're the .NET FX expert...

**Comment by tarekgh** [comment] 2022-06-28 18:13
@ArchiDog1998 You may look at the internal class https://github.com/dotnet/TorchSharp/blob/49910eceb6a6ed3b99103a5c1782f6b5b802021a/src/TorchSharp/netstandard.cs#L180 and copy the code as needed. I assume you want to load a native library.

**Comment by NiklasGustafsson** [comment] 2022-06-28 18:17
@ArchiDog1998 -- which TorchSharp NuGet package are you using in your project?

**Comment by ArchiDog1998** [comment] 2022-07-01 01:38
I'm sorry, I'm new here. I've put a [Demo](https://github.com/ArchiDog1998/GHTorch/tree/master/TorchConsole) to Github. But I got an exception.
![BadImage](https://user-images.githubusercontent.com/53346444/176804710-ef6ed142-fac4-41cb-9704-999c6816aacd.png)
I've put _TorchSharp.dll_ and _LibTorchSharp.dll_ to the output file.
![File](https://user-images.githubusercontent.com/53346444/176805118-cfa52ec0-f368-4fe5-8b79-b723d0988b34.png)
And I made a [cpp console project](https://github.com/ArchiDog1998/GHTorch/tree/master/GHTorch.Console), which works fine.
So, any way to solve it?

**Comment by tarekgh** [comment] 2022-07-01 18:01
Try to use a project file like the following: 

Note, this if you want to run the app on Windows and using Cuda. If you want to use CPU instead, use the package `libtorch-cpu` instead of `TorchSharp-cuda-windows`


```Xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="libtorch-cuda-11.3-win-x64" Version="1.11.0.1" />
    <PackageReference Include="TorchSharp" Version="0.96.8" />
    <PackageReference Include="TorchSharp-cuda-windows" Version="0.96.8" />
  </ItemGroup>

</Project>
```

Then you can run `dotnet publish -r win-x64` to publish all binaries to the output publish folder. This should make your app run just fine.

**Comment by tarekgh** [comment] 2022-07-01 18:08
forgot to mention, in the app initialization code I added the following line to specify I want to run on GPU. You'll need to include this line too. 

```C#
        torch.InitializeDeviceType(DeviceType.CUDA);
```

**Comment by ArchiDog1998** [comment] 2022-07-02 02:37
Thanks a lot! I've succeed to create a tensor in .Net framework 4.8! So I create a dll as a base library, use a console software to use it, it works. But actually I want to create a plugin for another software called Rhinoceros 3D. So I create a plugin file referenced my base library, it failed. I found that `LibtorchSharp.dll` is not load in Rhinoceros 3D. And raise the same exception like my first comment. So how could I load this `LibtorchSharp.dll` manually?

**Comment by tarekgh** [comment] 2022-07-04 19:55
How do you deploy the `Rhinoceros 3D` plugin? I think the issue in your case is not manually loading the native DLL, but the issue is how you restore and deploy the native DLL with your library. Did you try to publish your library? (Using dotnet publish) as I mentioned earlier?

**Comment by tarekgh** [comment] 2022-07-11 16:33
I have manually run publish command `dotnet publish -r win-x64` and I am seeing all native bits get published fine. 

```
        Directory: C:\Temp\GHTorch-master\GHTorch\bin\Debug\net48\win-x64\publish

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---          6/2/2022  10:47 AM         273408   asmjit.dll
-a---          6/2/2022  10:47 AM         370688   c10_cuda.dll
-a---          6/2/2022  10:47 AM         409088   c10.dll
-a---          6/2/2022  10:47 AM          16384   caffe2_nvrtc.dll
-a---          6/2/2022  10:47 AM      107136512   cublas64_11.dll
-a---          6/2/2022  10:47 AM      174900224   cublasLt64_11.dll
-a---          6/2/2022  10:47 AM         497664   cudart64_110.dll
-a---          6/2/2022  10:48 AM      130537472   cudnn_adv_infer64_8.dll
-a---          6/2/2022  10:48 AM       86708224   cudnn_adv_train64_8.dll
-a---          7/1/2022  10:18 AM      652900352   cudnn_cnn_infer64_8.dll
-a---          6/2/2022  10:48 AM             64   cudnn_cnn_infer64_8.dll.sha
-a---          6/2/2022  10:48 AM      167770624   cudnn_cnn_train64_8.dll
-a---          6/2/2022  10:48 AM      273885184   cudnn_ops_infer64_8.dll
-a---          6/2/2022  10:48 AM       58938368   cudnn_ops_train64_8.dll
-a---          6/2/2022  10:48 AM         223744   cudnn64_8.dll
-a---          6/2/2022  10:48 AM      188564992   cufft64_10.dll
-a---          6/2/2022  10:48 AM         285696   cufftw64_10.dll
-a---          6/2/2022  10:48 AM        3848192   cupti64_2021.1.0.dll
-a---          6/2/2022  10:48 AM       60747776   curand64_10.dll
-a---          6/2/2022  10:48 AM      209687552   cusolver64_11.dll
-a---          6/2/2022  10:48 AM      215774720   cusolverMg64_11.dll
-a---          6/2/2022  10:48 AM      224918016   cusparse64_11.dll
-a---        11/10/2020  11:21 AM         727552   Eto.dll
-a---          6/2/2022  10:48 AM        3854336   fbgemm.dll
-a---         7/11/2022   9:22 AM          19456   GHTorch.gha
-a---         7/11/2022   9:22 AM          16580   GHTorch.pdb
-a---         7/11/2022   9:22 AM           4096   GHTorch.TorchSharp.dll
-a---         7/11/2022   9:22 AM           8320   GHTorch.TorchSharp.pdb
-a---         7/11/2022   9:22 AM           9728   GHTorch.Wrapper.dll
-a---         7/11/2022   9:22 AM           9860   GHTorch.Wrapper.pdb
-a---         9/19/2021   2:20 AM         204800   ICSharpCode.SharpZipLib.dll
-a---          6/2/2022  10:48 AM        1959528   libiomp5md.dll
-a---          6/2/2022  10:48 AM          41576   libiompstubs5md.dll
-a---         6/21/2022   9:42 AM        1677120   LibTorchSharp.dll
-a---          6/2/2022  10:48 AM        5702656   nvrtc-builtins64_113.dll
-a---          6/2/2022  10:48 AM       32323584   nvrtc64_112_0.dll
-a---          6/2/2022  10:48 AM          48128   nvToolsExt64_1.dll
-a---        11/10/2020  11:21 AM       16522240   Rhino.UI.dll
-a---        11/10/2020  11:21 AM        3224576   RhinoCommon.dll
-a---         7/19/2017   3:01 AM          27992   System.Buffers.dll
-a---         4/17/2019   9:24 AM         148760   System.Memory.dll
-a---         7/19/2017   3:01 AM         115936   System.Numerics.Vectors.dll
-a---         9/18/2018  12:38 PM          23600   System.Runtime.CompilerServices.Unsafe.dll
-a---          6/2/2022  10:47 AM      219635712   torch_cpu.dll
-a---          6/2/2022  10:48 AM         986624   torch_cuda_cpp.dll
-a---          7/1/2022  10:18 AM      865411072   torch_cuda_cu.dll
-a---          6/2/2022  10:48 AM             64   torch_cuda_cu.dll.sha
-a---          6/2/2022  10:48 AM           9728   torch_cuda.dll
-a---          6/2/2022  10:48 AM           9728   torch_global_deps.dll
-a---          6/2/2022  10:48 AM           9728   torch.dll
-a---         6/21/2022   9:42 AM         551240   TorchSharp.dll
-a---          6/2/2022  10:48 AM         195072   uv.dll
-a---          6/2/2022  10:48 AM          89088   zlibwapi.dll
```

Even I have commented all manual copying you were doing in the csproj files, like:

```Xml
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="Copy &quot;$(TargetPath)&quot; &quot;E:\Software\Pytorch\libtorch-win-shared-with-deps-1.11.0+cu113\libtorch\lib\$(ProjectName).dll&quot;" />
	</Target>
```

Any more details can help to tell what is wrong. Did you use the whole contents of the `publish` folder when deploying your bits to use it as a plugin? How did you do that? Does the failure happen when running `Rhinoceros 3D`? and what is the calling stack when the failure occurs?

**Comment by NiklasGustafsson** [comment] 2022-09-22 01:36
This has been dormant for a long time. I will close the issue unless there's a response.

**Comment by NiklasGustafsson** [comment] 2022-09-22 01:37
This has been dormant for a long time, with no response. Please reopen if you have more information.

**Closed by NiklasGustafsson** 2022-09-22 01:37 UTC
