### ISSUE TITLE
How use it with Mac M1?

### ISSUE THREAD

**Issue by K-Mike** [dotnet/TorchSharp#876] opened 2022-12-27 13:23 UTC

**Comment by ChengYen-Tang** [comment] 2022-12-29 03:04
Maybe this will help you
https://github.com/dotnet/TorchSharp#download

**Comment by NiklasGustafsson** [comment] 2023-01-03 16:19
Support for M1 has not been added yet. I do not have access to a Mac with an M1 chip, but we have migrated to libtorch 1.13, so the backend support should be in place if someone with an M1 is willing to do the integration work.

Adding @dayo05

**Comment by dayo05** [comment] 2023-01-03 17:01
In temporary #837 can be the solution

**Comment by MovGP0** [comment] 2023-02-19 13:22
See also #652 and #643

**Comment by NiklasGustafsson** [comment] 2023-10-20 19:18
Duplicate of 652 -- no need to track separately. As soon as someone gives me a machine with M1/M2 HW, I'll jump on this... :-)

**Closed by NiklasGustafsson** 2023-10-20 19:18 UTC

**Comment by NiklasGustafsson** [comment] 2024-02-27 22:53
Update: This was addressed in v0.102.0
