### ISSUE TITLE
Unittest `TestTorchAudio.TestGriffinLim` sometimes fails

### ISSUE THREAD

**Issue by kaiidams** [dotnet/TorchSharp#704] opened 2022-08-17 13:46 UTC
Probably related to `torch.stft()`?

https://dev.azure.com/dotnet/TorchSharp/_build/results?buildId=76663&view=logs&j=2812c918-a321-5e19-5b29-10363f5e248a&t=302e1c24-6f59-5c96-e596-a4fa20fb02a1&l=180

**Comment by kaiidams** [comment] 2022-08-17 14:11
Is it possible to replace _shape with different data size? https://github.com/dotnet/TorchSharp/blob/2398b2e20289b5472ff41bb315f04627e78fb2a4/src/TorchSharp/Tensor/Tensor.cs#L7115

**Comment by NiklasGustafsson** [comment] 2022-08-17 14:22
@kaiidams -- thanks for pointing this out. A pretty stupid mistake on my part -- `var _shape = shape;` doesn't create a copy, of course.

**Comment by NiklasGustafsson** [comment] 2022-08-17 14:45
@kaiidams -- I looked at the code and made what was meant to be a silly comment about myself and my mistakes in coding here. I realized that either one of us could have written that code, so I removed that commend. I apologize if it was you who wrote that code. I only meant to make fun of myself.

Yes, the problem is that `var _size = shape;` doesn't actually make a copy, so any modifications to the _size elements, will also modify the shape of the current tensor.

I have made a change to the code and it will be part of the release prep PR. I'll ask you to review.

**Closed** 2022-08-17 15:39 UTC
